import tailwind from "bun-plugin-tailwind";
import { cpSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { config } from "../src/config";

/**
 * The GitHub Pages build (baas/site.md §2a): hashed assets under the
 * configured base path, `404.html` as the SPA deep-link fallback, and
 * `.nojekyll` so Pages serves every asset. `bun run build` → dist/ is
 * the whole deployment.
 */

const out = new URL("../dist/", import.meta.url).pathname;
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const result = await Bun.build({
  entrypoints: [new URL("../index.html", import.meta.url).pathname],
  outdir: out,
  plugins: [tailwind],
  minify: true,
  naming: { chunk: "assets/[name]-[hash].[ext]", asset: "assets/[name]-[hash].[ext]" },
  // Asset URLs must resolve under the Pages base path ("" ≡ site root).
  publicPath: `${config.basename}/`,
});
if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// The manifest is a REIFIED artifact (sync artifacts → public/), so the
// bundler never sees it — the link is injected post-build, base-path'd.
for (const name of ["index.html"]) {
  const target = `${out}${name}`;
  const html = await Bun.file(target).text();
  await Bun.write(
    target,
    html.replace(
      "</head>",
      `<link rel="icon" type="image/svg+xml" href="${config.basename}/favicon.svg">` +
        `<link rel="manifest" href="${config.basename}/manifest.webmanifest"></head>`,
    ),
  );
}

// Pages has no rewrites: 404.html IS the SPA shell, so deep links recover.
cpSync(`${out}index.html`, `${out}404.html`);

// ---------------------------------------------------------------------------
// SEO artifacts (site.md §2, reified at build): sitemap, robots, llms.txt.
// ---------------------------------------------------------------------------
const SITE = "https://mahmoodkhalil57.github.io" + config.basename;
const ROUTES = ["/", "/products", "/blog", "/contact", "/login"];
await Bun.write(
  `${out}sitemap.xml`,
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    ROUTES.map((r) => `  <url><loc>${SITE}${r === "/" ? "" : r}</loc></url>`).join("\n") +
    `\n</urlset>\n`,
);
await Bun.write(`${out}robots.txt`, `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`);
await Bun.write(
  `${out}llms.txt`,
  `# saastarter2\n\n> The self-aware SaaS template: an ecommerce shop that sells its own source code.\n\n` +
    `Static react-router storefront (GitHub Pages) over a declarative baas (Cloudflare Workers).\n` +
    `Everything server-side is a hosted capability: collections, auth pools, commerce, billing, search.\n\n` +
    `## Pages\n${ROUTES.map((r) => `- ${SITE}${r === "/" ? "" : r}`).join("\n")}\n\n` +
    `## API\n- OpenAPI: ${config.endpoint}/v1/projects/${config.project}/openapi.json\n- MCP: ${config.endpoint}/v1/projects/${config.project}/mcp\n`,
);

// ---------------------------------------------------------------------------
// PWA service worker: versioned cache, precached shell, network-first
// navigations with shell fallback, cache-first hashed assets, network-first
// /v1 GETs. No clients.claim (control begins next navigation). Base-pathed.
// ---------------------------------------------------------------------------
const shell = [`${config.basename}/`, `${config.basename}/manifest.webmanifest`, `${config.basename}/favicon.svg`, `${config.basename}/icon.svg`];
const walk = (dir: string, prefix: string): string[] =>
  Array.from(new Bun.Glob("**/*").scanSync({ cwd: dir })).map((f) => `${prefix}/${f}`);
const hashed = walk(`${out}assets`, `${config.basename}/assets`);
const version = Bun.hash(JSON.stringify(hashed)).toString(36);
await Bun.write(
  `${out}sw.js`,
  `/* generated by scripts/build.ts — do not edit */
const CACHE = "shell-${version}";
const BASE = ${JSON.stringify(config.basename)};
const PRECACHE = ${JSON.stringify([...shell, ...hashed])};
self.addEventListener("install", (e) => e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())));
self.addEventListener("activate", (e) =>
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))));
self.addEventListener("message", (e) => { if (e.data && e.data.type === "SKIP_WAITING") self.skipWaiting(); });
const put = async (req, res) => { if (res && res.ok) (await caches.open(CACHE)).put(req, res.clone()); return res; };
const networkFirst = async (req, fb) => {
  try { return await put(req, await fetch(req)); }
  catch { const c = await caches.match(req); if (c) return c; if (fb) { const s = await caches.match(fb); if (s) return s; } throw new Error("offline"); }
};
const cacheFirst = async (req) => (await caches.match(req)) ?? put(req, await fetch(req));
self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.hostname === "fonts.googleapis.com" || url.hostname === "fonts.gstatic.com") return event.respondWith(cacheFirst(req));
  if (url.pathname.startsWith("/v1/")) return event.respondWith(networkFirst(req));
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") return event.respondWith(networkFirst(req, BASE + "/"));
  if (url.pathname.startsWith(BASE + "/assets/")) return event.respondWith(cacheFirst(req));
});
`,
);
// Jekyll would eat underscore-prefixed asset paths — opt out.
await Bun.write(`${out}.nojekyll`, "");
// Static extras (icons, reified SEO/PWA artifacts once site.md §2 lands).
const publicDir = new URL("../public/", import.meta.url).pathname;
if (existsSync(publicDir)) cpSync(publicDir, out, { recursive: true });

console.log(`built → dist/ (base path "${config.basename || "/"}", 404.html + .nojekyll in place)`);
